remote_theme: fongandrew/hydeout@v4.2.0

# Dependencies
markdown:     kramdown
highlighter:  rouge

# Home Page Setup
title:       'Jordan Ruggles'
description: 'Ideally within walking distance of an Internet Pitstop in case something breaks down.'
#description: 'A corner of the Internet where I can consolidate my projects, share what I\'m comfortable sharing, & stash away a time capsule of joy.'
url:          https://jorugg.github.io
baseurl:      /

author:       'Jordan Ruggles'

paginate:     3

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-target-blank

sidebar_home_link:  true
