remote_theme: poole/hyde

# Dependencies
#markdown:     kramdown
#highlighter:  rouge

# Home Page Setup
title: 'Jordan Ruggles'
description: 'Ideally within walking distance of an Internet Pitstop for when something breaks down'
#description: 'A corner of the Internet where I can consolidate my projects, share what I\'m comfortable sharing, & stash away a time capsule of joy.'
url:          https://jorugg.github.io

author:       'Jordan Ruggles'

paginate:     5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
